[features]
seeds = false
skip-lint = false
[programs.localnet]
whitelist_gated_sale = "CRKtvQJeuqgASZzoSFnRh65ihHRVyMzidrw7sQmfYKi7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/maskyray/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
