[features]
seeds = false
skip-lint = false
[programs.devnet]
whitelist_gated_sale = "CRKtvQJeuqgASZzoSFnRh65ihHRVyMzidrw7sQmfYKi7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
